# Generated by Django 3.1.7 on 2021-03-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('score_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalk_hit', models.BooleanField(default=False)),
                ('face_hit', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('target_hit', models.PositiveIntegerField(blank=True, null=True)),
                ('date_played', models.DateTimeField()),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.player')),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
